name: DeepProtFunc
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - appdirs=1.4.4=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py39h06a4308_0
  - cffi=1.15.1=py39h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=38.0.4=py39h9ce1e76_0
  - cudatoolkit=11.3.1=ha36c431_9
  - ffmpeg=4.3=hf484d3e_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py39h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - lightgbm=3.3.5=py39h6a678d5_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.23.5=py39h14f4228_0
  - numpy-base=1.23.5=py39h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=23.0=py39h06a4308_0
  - pillow=9.3.0=py39hace64e9_1
  - pip=22.3.1=py39h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.13=haa1d7c7_2
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py39h06a4308_0
  - scikit-learn=1.2.1=py39h6a678d5_0
  - setuptools=65.6.3=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py39_cu113
  - torchvision=0.13.1=py39_cu113
  - typing_extensions=4.4.0=py39h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.14=py39h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - biopython==1.80
      - biotite==0.35.0
      - cachetools==5.3.0
      - contourpy==1.0.7
      - crc32c==2.3.post0
      - cycler==0.11.0
      - filelock==3.9.0
      - flatbuffers==23.1.21
      - fonttools==4.38.0
      - gast==0.4.0
      - gemmi==0.5.8
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.51.1
      - h5py==3.8.0
      - huggingface-hub==0.12.0
      - importlib-metadata==6.0.0
      - interchange==2021.0.4
      - joblib==1.2.0
      - keras==2.11.0
      - kiwisolver==1.4.4
      - libclang==15.0.6.1
      - markdown==3.4.1
      - markupsafe==2.1.2
      - matplotlib==3.6.3
      - mock==5.0.1
      - monotonic==1.6
      - msgpack==1.0.4
      - networkx==3.0
      - oauthlib==3.2.2
      - obonet==0.3.1
      - opt-einsum==3.3.0
      - pandas==1.5.3
      - pansi==2020.7.3
      - pickle5==0.0.11
      - protobuf==3.19.6
      - py2neo==2021.2.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygments==2.14.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - pyyaml==6.0
      - regex==2022.10.31
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scipy==1.10.1
      - seaborn==0.12.2
      - subword-nmt==0.3.8
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.5.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.30.0
      - termcolor==2.2.0
      - tfrecord==1.14.1
      - threadpoolctl==3.1.0
      - tokenizers==0.13.2
      - tqdm==4.64.1
      - transformers==4.26.0
      - werkzeug==2.2.2
      - wget==3.2
      - wrapt==1.14.1
      - xgboost==1.7.3
      - zipp==3.12.0
